import nodemailer from 'nodemailer';
import type { SmtpConfig } from '../config/schema.js';

/**
 * The thinnest wrapper around nodemailer that this project needs.
 *
 * WHY A WRAPPER AND NOT nodemailer DIRECTLY. Two reasons. First, credentials
 * belong to this module and nowhere else - a caller who imported nodemailer
 * directly could log the transporter and leak the password. Second, a caller
 * has no business knowing which SMTP library ships underneath. If nodemailer
 * changes shape, this file changes; every caller keeps working.
 *
 * NEVER THROWS. A sync run that succeeded but could not send a notification
 * must still finish. `sendMail` returns a result so a caller can log the
 * failure without one, but the sync itself is never derailed by the mailer.
 */

export interface MailEnvelope {
  readonly to: string;
  readonly subject: string;
  /** Plain-text body. HTML alternative is generated by escaping and paragraphing. */
  readonly text: string;
}

export interface MailResult {
  readonly ok: boolean;
  readonly detail?: string;
}

export interface SmtpClient {
  send(envelope: MailEnvelope): Promise<MailResult>;
}

export function createSmtpClient(config: SmtpConfig): SmtpClient {
  // The transport options are typed loosely upstream; casting through a
  // TransportOptions view keeps the field-shape check where we own it.
  const transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.port === 465,
    auth: {
      user: config.user,
      pass: config.password,
    },
  } as nodemailer.TransportOptions);

  return {
    async send(envelope) {
      try {
        await transporter.sendMail({
          from: config.from,
          to: envelope.to,
          subject: envelope.subject,
          text: envelope.text,
          html: toHtml(envelope.text),
        });
        return { ok: true };
      } catch (error) {
        // Never throw - see the header. Report the failure class rather than
        // the message, because SMTP libraries habitually put credentials into
        // errors and this text ends up in a log.
        return { ok: false, detail: error instanceof Error ? error.name : 'unknown error' };
      }
    },
  };
}

/** A no-op mailer for tests and for runs where SMTP is not configured. */
export function nullSmtpClient(): SmtpClient {
  return { send: () => Promise.resolve({ ok: true }) };
}

const ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escape(text: string): string {
  return text.replace(/[&<>"']/g, (c) => ESCAPE_MAP[c] ?? c);
}

function toHtml(text: string): string {
  const paragraphs = text
    .split(/\n{2,}/)
    .map((p) => `<p>${escape(p).replace(/\n/g, '<br>')}</p>`)
    .join('');
  return `<!doctype html><html><body>${paragraphs}</body></html>`;
}
